/**
 * ASCII v1 — glyph-based rendering
 * (POST_MVP_ASCII_AND_ANIMATED_ASCII_PHASE_1).
 *
 * ASCII IS NOT DITHER AND IS NOT TEXTURE. Texture adds a PATTERN to the
 * surface. Dither reduces final TONE through a threshold map. ASCII replaces
 * regions of the surface with CHARACTER GLYPHS: the frame is divided into a
 * monospace cell grid, each cell picks a character based on its brightness,
 * and that character's 5x5 bitmap is drawn.
 *
 * NO FONT, NO TEXTURE ATLAS. Shaders have no text rendering, so each glyph is
 * stored as a 5x5 bitmap packed into bits: bit index = x + 5*y. Testing one bit
 * tells you whether that pixel of the character is filled. The tables in
 * `GLYPH_TABLE_GLSL` are generated by `scripts/gen/glyphs.py` (which validates
 * against a published reference encoding) rather than hand-typed.
 *
 * PRECISION NOTE: a full 5x5 block is 2^25-1, but GLSL highp floats only hold
 * integers exactly up to 2^24. Every glyph is therefore split into a lo (13
 * bit) / hi (12 bit) pair, and the bit test picks the half it needs. Storing
 * the raw 25-bit value as one float would silently corrupt the densest glyphs.
 *
 * HONEST LIMITATION: this runs inside the MATERIAL shader, not as a
 * post-process pass. A fragment can only see its own shaded value, never the
 * average over its cell, so the character is chosen from per-pixel luminance
 * rather than cell-mean luminance. In practice the shaded stroke varies
 * smoothly and the ramp is coarsely quantized (3-10 levels), so almost every
 * cell resolves to a single character; a cell straddling a luminance boundary
 * can show two. True cell-averaging needs a post-process pass, which is a
 * later phase.
 *
 * Research: docs/research/ascii-phase.md. Explainer: docs/explainers/03-ascii.md
 */
import type * as THREE from "three"
import type { AsciiCharset, AsciiDirection } from "./style-system"

export const ASCII_CHARSET_INDEX: Record<AsciiCharset, number> = {
  classic: 0,
  blocks: 1,
  minimal: 2,
  dots: 3,
  custom: 4,
}

/** Number of glyphs in each charset ramp (must match scripts/gen/glyphs.py). */
export const ASCII_RAMP_LENGTH: Record<AsciiCharset, number> = {
  classic: 10,
  blocks: 5,
  minimal: 3,
  dots: 6,
  custom: 7,
}

/** Distinct animated-ASCII behaviours. Each moves a DIFFERENT thing. */
export type AsciiAnimationType =
  | "none"
  | "scroll"
  | "rain"
  | "cycle"
  | "flicker"
  | "revealDensity"

export const ASCII_ANIM_INDEX: Record<AsciiAnimationType, number> = {
  none: 0,
  scroll: 1,
  rain: 2,
  cycle: 3,
  flicker: 4,
  revealDensity: 5,
}

export const ASCII_DIRECTION_VEC: Record<AsciiDirection, [number, number]> = {
  static: [0, 0],
  horizontal: [1, 0],
  vertical: [0, 1],
}

export interface AsciiUniforms {
  uFsAscOn: { value: number }
  uFsAscCharset: { value: number }
  uFsAscCell: { value: number }
  uFsAscDensity: { value: number }
  uFsAscContrast: { value: number }
  uFsAscAnim: { value: number }
  uFsAscTime: { value: number }
  uFsAscDirX: { value: number }
  uFsAscDirY: { value: number }
  uFsAscLockScreen: { value: number }
  /** Draw-in reveal progress, for revealDensity. */
  uFsAscReveal: { value: number }
}

export function createAsciiUniforms(): AsciiUniforms {
  return {
    uFsAscOn: { value: 0 },
    uFsAscCharset: { value: 0 },
    uFsAscCell: { value: 8 },
    uFsAscDensity: { value: 0.5 },
    uFsAscContrast: { value: 0.5 },
    uFsAscAnim: { value: 0 },
    uFsAscTime: { value: 0 },
    uFsAscDirX: { value: 0 },
    uFsAscDirY: { value: 0 },
    uFsAscLockScreen: { value: 1 },
    uFsAscReveal: { value: 1 },
  }
}

const GLYPH_TABLE_GLSL = /* glsl */ `
vec2 fsGlyphBits(int idx) {
  if (idx == 0) return vec2(0.0, 0.0); // space
  if (idx == 1) return vec2(0.0, 512.0); // dot
  if (idx == 2) return vec2(128.0, 16.0); // colon
  if (idx == 3) return vec2(6144.0, 1.0); // dash
  if (idx == 4) return vec2(448.0, 56.0); // equal
  if (idx == 5) return vec2(6272.0, 17.0); // plus
  if (idx == 6) return vec2(6816.0, 85.0); // star
  if (idx == 7) return vec2(3050.0, 1405.0); // hash
  if (idx == 8) return vec2(4467.0, 3304.0); // pct
  if (idx == 9) return vec2(5934.0, 1830.0); // at
  if (idx == 10) return vec2(5141.0, 2690.0); // shade1
  if (idx == 11) return vec2(5461.0, 2730.0); // shade2
  if (idx == 12) return vec2(7871.0, 4055.0); // shade3
  if (idx == 13) return vec2(8191.0, 4095.0); // block
  if (idx == 14) return vec2(4292.0, 1808.0); // one
  if (idx == 15) return vec2(1582.0, 1862.0); // zero
  if (idx == 16) return vec2(4096.0, 0.0); // d1
  if (idx == 17) return vec2(64.0, 32.0); // d2
  if (idx == 18) return vec2(1028.0, 514.0); // d3
  if (idx == 19) return vec2(4113.0, 2176.0); // d4
  if (idx == 20) return vec2(2069.0, 2689.0); // d5
  if (idx == 21) return vec2(4368.0, 136.0); // slash
  if (idx == 22) return vec2(130.0, 273.0); // gt
  if (idx == 23) return vec2(2184.0, 1040.0); // lt
  if (idx == 24) return vec2(2188.0, 1552.0); // lbrc
  if (idx == 25) return vec2(2126.0, 1800.0); // lbr
  return vec2(0.0, 0.0);
}

// charset ramp lookup: (charset, level) -> global glyph index
int fsRampIndex(int charset, int level) {
  if (charset == 0) { // classic
    if (level <= 0) return 0;
    if (level <= 1) return 1;
    if (level <= 2) return 2;
    if (level <= 3) return 3;
    if (level <= 4) return 4;
    if (level <= 5) return 5;
    if (level <= 6) return 6;
    if (level <= 7) return 7;
    if (level <= 8) return 8;
    if (level <= 9) return 9;
    return 9;
  }
  if (charset == 1) { // blocks
    if (level <= 0) return 0;
    if (level <= 1) return 10;
    if (level <= 2) return 11;
    if (level <= 3) return 12;
    if (level <= 4) return 13;
    return 13;
  }
  if (charset == 2) { // minimal
    if (level <= 0) return 0;
    if (level <= 1) return 14;
    if (level <= 2) return 15;
    return 15;
  }
  if (charset == 3) { // dots
    if (level <= 0) return 0;
    if (level <= 1) return 16;
    if (level <= 2) return 17;
    if (level <= 3) return 18;
    if (level <= 4) return 19;
    if (level <= 5) return 20;
    return 20;
  }
  if (charset == 4) { // custom
    if (level <= 0) return 0;
    if (level <= 1) return 1;
    if (level <= 2) return 21;
    if (level <= 3) return 22;
    if (level <= 4) return 23;
    if (level <= 5) return 24;
    if (level <= 6) return 25;
    return 25;
  }
  return 0;
}
`

export const ASCII_COMMON_GLSL = /* glsl */ `
uniform float uFsAscOn;
uniform float uFsAscCharset;
uniform float uFsAscCell;
uniform float uFsAscDensity;
uniform float uFsAscContrast;
uniform float uFsAscAnim;
uniform float uFsAscTime;
uniform float uFsAscDirX;
uniform float uFsAscDirY;
uniform float uFsAscLockScreen;
uniform float uFsAscReveal;

${GLYPH_TABLE_GLSL}

// Cheap per-cell hash, for flicker / rain column offsets.
float fsAscHash(vec2 p) {
  return fract(sin(dot(p, vec2(41.7, 289.3))) * 27183.19);
}

// Is pixel (gx, gy) of glyph idx filled? Bit index = gx + 5*gy, split across
// the lo/hi halves because a 25-bit value does not survive as a single float.
float fsGlyphPixel(int idx, vec2 g) {
  if (g.x < 0.0 || g.x > 4.0 || g.y < 0.0 || g.y > 4.0) return 0.0;
  vec2 bits = fsGlyphBits(idx);
  float a = g.x + 5.0 * g.y;
  float src = a < 13.0 ? bits.x : bits.y;
  float shift = a < 13.0 ? a : a - 13.0;
  return mod(floor(src / pow(2.0, shift)), 2.0);
}
`

/** Fragment tail: replace the shaded surface with character glyphs. */
export const ASCII_FRAGMENT_GLSL = /* glsl */ `
if (uFsAscOn > 0.5) {
  // --- 1. the cell grid -------------------------------------------------
  vec2 fsACo = uFsAscLockScreen > 0.5
    ? gl_FragCoord.xy / max(uFsAscCell, 2.0)
    : vFsObjPos.xy * (150.0 / max(uFsAscCell, 2.0));

  vec2 fsDir = vec2(uFsAscDirX, uFsAscDirY);
  if (uFsAscAnim > 0.5 && uFsAscAnim < 1.5) {
    fsACo += fsDir * uFsAscTime;                 // scroll: whole grid travels
  } else if (uFsAscAnim < 2.5 && uFsAscAnim > 1.5) {
    // rain: each COLUMN falls at its own speed, so glyphs stream downward
    float col = floor(fsACo.x);
    fsACo.y += uFsAscTime * (0.6 + fsAscHash(vec2(col, 3.0)) * 1.8);
  }

  vec2 fsCell = floor(fsACo);
  vec2 fsInCell = fract(fsACo);

  // --- 2. brightness -> which character ---------------------------------
  vec3 fsAC = gl_FragColor.rgb;
  float fsARaw = dot(fsAC, vec3(0.2126, 0.7152, 0.0722));

  // EXPOSURE. Free Stroke's ink is near-black: a shaded stroke occupies only
  // the bottom ~15% of the 0..1 luminance range. Feeding that straight into
  // the ramp would only ever select the two sparsest characters, so the whole
  // form reads as empty. Dividing by a reference luminance rescales the
  // subject's actual range onto the full ramp. Density IS that reference:
  // a low reference means dimmer pixels already count as "bright", which
  // selects denser characters.
  float fsRef = mix(1.1, 0.16, clamp(uFsAscDensity, 0.0, 1.0));
  float fsALum = clamp(fsARaw / max(fsRef, 0.02), 0.0, 1.0);
  // Gentle contrast only. A hard expansion here crushes the shading variation
  // that makes DIFFERENT characters appear across the form — over-expand and
  // every cell saturates to the densest glyph, which reads as a flat mesh
  // rather than as text.
  fsALum = clamp((fsALum - 0.5) * (0.7 + uFsAscContrast * 1.1) + 0.5, 0.0, 1.0);

  float fsRampMax = max(uFsAscCharset > 3.5 ? 6.0
                      : uFsAscCharset > 2.5 ? 5.0
                      : uFsAscCharset > 1.5 ? 2.0
                      : uFsAscCharset > 0.5 ? 4.0 : 9.0, 1.0);
  float fsLevel = floor(fsALum * fsRampMax + 0.5);

  if (uFsAscAnim > 2.5 && uFsAscAnim < 3.5) {
    // cycle: every cell walks up the ramp over time (glyphs change in place)
    fsLevel = mod(fsLevel + floor(uFsAscTime * 3.0), fsRampMax + 1.0);
  } else if (uFsAscAnim > 3.5 && uFsAscAnim < 4.5) {
    // flicker: a few cells jump to a random glyph each tick
    float tick = floor(uFsAscTime * 8.0);
    float r = fsAscHash(fsCell + tick);
    if (r > 0.86) fsLevel = floor(fsAscHash(fsCell + tick + 7.0) * fsRampMax + 0.5);
  } else if (uFsAscAnim > 4.5) {
    // revealDensity: characters thicken as the stroke draws in
    fsLevel = floor(fsLevel * clamp(uFsAscReveal, 0.0, 1.0) + 0.5);
  }

  int fsIdx = fsRampIndex(int(uFsAscCharset + 0.5), int(fsLevel + 0.5));

  // --- 3. draw the glyph ------------------------------------------------
  // 5x5 bitmap sampled inside the cell. floor(inCell * 5) gives the pixel of
  // the character; y is flipped because glyph row 0 is the TOP row while
  // gl_FragCoord.y grows upward.
  vec2 fsG = floor(vec2(fsInCell.x, 1.0 - fsInCell.y) * 5.0);
  float fsOn = fsGlyphPixel(fsIdx, fsG);

  // Lit glyph pixels must be MUCH brighter than unlit ones or the characters
  // are invisible on dark ink (multiplying near-black by 1.35 is still
  // near-black). Divide the colour by its own luminance to get the surface's
  // hue with brightness normalised away, then drive brightness explicitly:
  // bright for lit glyph pixels, near-black for the rest. This keeps material
  // presets distinguishable instead of collapsing every surface to white.
  vec3 fsATint = fsARaw > 0.002 ? fsAC / fsARaw : vec3(1.0);
  vec3 fsOnCol = clamp(fsATint * 0.82, 0.0, 1.0);
  vec3 fsOffCol = clamp(fsATint * 0.05, 0.0, 1.0);
  gl_FragColor.rgb = mix(fsOffCol, fsOnCol, fsOn);
}
`

/** Standalone install (unused when the composer is active; kept for parity). */
export function applyAsciiShader(material: THREE.Material, uniforms: AsciiUniforms): void {
  material.onBeforeCompile = (shader) => {
    Object.assign(shader.uniforms, uniforms)
    shader.vertexShader = shader.vertexShader
      .replace("#include <common>", "#include <common>\nvarying vec3 vFsObjPos;")
      .replace("#include <begin_vertex>", "#include <begin_vertex>\nvFsObjPos = position;")
    shader.fragmentShader = shader.fragmentShader
      .replace("#include <common>", `#include <common>\nvarying vec3 vFsObjPos;\n${ASCII_COMMON_GLSL}`)
      .replace("#include <dithering_fragment>", `#include <dithering_fragment>\n${ASCII_FRAGMENT_GLSL}`)
  }
  material.customProgramCacheKey = () => "freestroke-ascii-v1"
}
