/**
 * ASCII v1 — glyph-based rendering
 * (POST_MVP_ASCII_AND_ANIMATED_ASCII_PHASE_1).
 *
 * ASCII IS NOT DITHER AND IS NOT TEXTURE. Texture adds a PATTERN to the
 * surface. Dither reduces final TONE through a threshold map. ASCII replaces
 * regions of the surface with CHARACTER GLYPHS: the frame is divided into a
 * monospace cell grid, each cell picks a character based on its brightness,
 * and that character's 5x5 bitmap is drawn.
 *
 * NO FONT, NO TEXTURE ATLAS. Shaders have no text rendering, so each glyph is
 * stored as a 5x5 bitmap packed into bits: bit index = x + 5*y. Testing one bit
 * tells you whether that pixel of the character is filled. The tables in
 * `GLYPH_TABLE_GLSL` are generated by `scripts/gen/glyphs.py` (which validates
 * against a published reference encoding) rather than hand-typed.
 *
 * PRECISION NOTE: a full 5x5 block is 2^25-1, but GLSL highp floats only hold
 * integers exactly up to 2^24. Every glyph is therefore split into a lo (13
 * bit) / hi (12 bit) pair, and the bit test picks the half it needs. Storing
 * the raw 25-bit value as one float would silently corrupt the densest glyphs.
 *
 * HONEST LIMITATION: this runs inside the MATERIAL shader, not as a
 * post-process pass. A fragment can only see its own shaded value, never the
 * average over its cell, so the character is chosen from per-pixel luminance
 * rather than cell-mean luminance. In practice the shaded stroke varies
 * smoothly and the ramp is coarsely quantized (3-10 levels), so almost every
 * cell resolves to a single character; a cell straddling a luminance boundary
 * can show two. True cell-averaging needs a post-process pass, which is a
 * later phase.
 *
 * Research: docs/research/ascii-phase.md. Explainer: docs/explainers/03-ascii.md
 */
import type * as THREE from "three"
import type { AsciiCharset, AsciiDirection } from "./style-system"

export const ASCII_CHARSET_INDEX: Record<AsciiCharset, number> = {
  classic: 0,
  blocks: 1,
  minimal: 2,
  dots: 3,
  custom: 4,
  braille: 5,
  boxes: 6,
  arrows: 7,
  punct: 8,
  numeric: 9,
}

/** Number of glyphs in each charset ramp (must match scripts/gen/glyphs.py). */
export const ASCII_RAMP_LENGTH: Record<AsciiCharset, number> = {
  classic: 10,
  blocks: 5,
  minimal: 3,
  dots: 6,
  custom: 7,
  braille: 7,
  boxes: 6,
  arrows: 7,
  punct: 8,
  numeric: 10,
}

/** Distinct animated-ASCII behaviours. Each moves a DIFFERENT thing. */
export type AsciiAnimationType =
  | "none"
  | "scroll"
  | "rain"
  | "cycle"
  | "flicker"
  | "revealDensity"

export const ASCII_ANIM_INDEX: Record<AsciiAnimationType, number> = {
  none: 0,
  scroll: 1,
  rain: 2,
  cycle: 3,
  flicker: 4,
  revealDensity: 5,
}

export const ASCII_DIRECTION_VEC: Record<AsciiDirection, [number, number]> = {
  static: [0, 0],
  horizontal: [1, 0],
  vertical: [0, 1],
}

export interface AsciiUniforms {
  uFsAscOn: { value: number }
  uFsAscCharset: { value: number }
  uFsAscCell: { value: number }
  uFsAscDensity: { value: number }
  uFsAscContrast: { value: number }
  uFsAscAnim: { value: number }
  uFsAscTime: { value: number }
  uFsAscDirX: { value: number }
  uFsAscDirY: { value: number }
  uFsAscLockScreen: { value: number }
  /** Draw-in reveal progress, for revealDensity. */
  uFsAscReveal: { value: number }
  /** How strongly the glyph result replaces the input (stack amount). */
  uFsAscAmount: { value: number }
  /** Stack blend mode (see STACK_BLEND_INDEX). */
  uFsAscBlend: { value: number }
}

export function createAsciiUniforms(): AsciiUniforms {
  return {
    uFsAscOn: { value: 0 },
    uFsAscCharset: { value: 0 },
    uFsAscCell: { value: 8 },
    uFsAscDensity: { value: 0.5 },
    uFsAscContrast: { value: 0.5 },
    uFsAscAnim: { value: 0 },
    uFsAscTime: { value: 0 },
    uFsAscDirX: { value: 0 },
    uFsAscDirY: { value: 0 },
    uFsAscLockScreen: { value: 1 },
    uFsAscReveal: { value: 1 },
    uFsAscAmount: { value: 1 },
    uFsAscBlend: { value: 0 },
  }
}

const GLYPH_TABLE_GLSL = /* glsl */ `
vec2 fsGlyphBits(int idx) {
  if (idx == 0) return vec2(0.0, 0.0); // space
  if (idx == 1) return vec2(0.0, 512.0); // dot
  if (idx == 2) return vec2(128.0, 16.0); // colon
  if (idx == 3) return vec2(6144.0, 1.0); // dash
  if (idx == 4) return vec2(448.0, 56.0); // equal
  if (idx == 5) return vec2(6272.0, 17.0); // plus
  if (idx == 6) return vec2(6816.0, 85.0); // star
  if (idx == 7) return vec2(3050.0, 1405.0); // hash
  if (idx == 8) return vec2(4467.0, 3304.0); // pct
  if (idx == 9) return vec2(5934.0, 1830.0); // at
  if (idx == 10) return vec2(5141.0, 2690.0); // shade1
  if (idx == 11) return vec2(5461.0, 2730.0); // shade2
  if (idx == 12) return vec2(7871.0, 4055.0); // shade3
  if (idx == 13) return vec2(8191.0, 4095.0); // block
  if (idx == 14) return vec2(4292.0, 1808.0); // one
  if (idx == 15) return vec2(1582.0, 1862.0); // zero
  if (idx == 16) return vec2(4096.0, 0.0); // d1
  if (idx == 17) return vec2(64.0, 32.0); // d2
  if (idx == 18) return vec2(1028.0, 514.0); // d3
  if (idx == 19) return vec2(4113.0, 2176.0); // d4
  if (idx == 20) return vec2(2069.0, 2689.0); // d5
  if (idx == 21) return vec2(4368.0, 136.0); // slash
  if (idx == 22) return vec2(130.0, 273.0); // gt
  if (idx == 23) return vec2(2184.0, 1040.0); // lt
  if (idx == 24) return vec2(2188.0, 1552.0); // lbrc
  if (idx == 25) return vec2(2126.0, 1800.0); // lbr
  if (idx == 26) return vec2(2048.0, 0.0); // b1
  if (idx == 27) return vec2(2050.0, 0.0); // b2
  if (idx == 28) return vec2(2050.0, 256.0); // b3
  if (idx == 29) return vec2(2058.0, 1280.0); // b4
  if (idx == 30) return vec2(2058.0, 1281.0); // b5
  if (idx == 31) return vec2(2378.0, 1321.0); // b6
  if (idx == 32) return vec2(4228.0, 528.0); // vline
  if (idx == 33) return vec2(7300.0, 531.0); // cross
  if (idx == 34) return vec2(3050.0, 1405.0); // lattice
  if (idx == 35) return vec2(1599.0, 4038.0); // frame
  if (idx == 36) return vec2(7871.0, 4055.0); // framecross
  if (idx == 37) return vec2(1348.0, 2.0); // caret
  if (idx == 38) return vec2(4161.0, 2080.0); // bslash
  if (idx == 39) return vec2(4433.0, 2216.0); // diagx
  if (idx == 40) return vec2(5572.0, 530.0); // arrowup
  if (idx == 41) return vec2(6272.0, 125.0); // tri
  if (idx == 42) return vec2(132.0, 0.0); // apos
  if (idx == 43) return vec2(330.0, 0.0); // quote
  if (idx == 44) return vec2(128.0, 272.0); // semi
  if (idx == 45) return vec2(4228.0, 512.0); // excl
  if (idx == 46) return vec2(4654.0, 513.0); // quest
  if (idx == 47) return vec2(2210.0, 1364.0); // amp
  if (idx == 48) return vec2(6334.0, 2001.0); // dollar
  if (idx == 49) return vec2(543.0, 529.0); // seven
  if (idx == 50) return vec2(4623.0, 1985.0); // three
  if (idx == 51) return vec2(7465.0, 1059.0); // four
  if (idx == 52) return vec2(4654.0, 3977.0); // two
  if (idx == 53) return vec2(7214.0, 1861.0); // six
  if (idx == 54) return vec2(6702.0, 1859.0); // nine
  if (idx == 55) return vec2(7231.0, 1985.0); // five
  if (idx == 56) return vec2(6702.0, 1861.0); // eight
  return vec2(0.0, 0.0);
}

// charset ramp lookup: (charset, level) -> global glyph index
int fsRampIndex(int charset, int level) {
  if (charset == 0) { // classic
    if (level <= 0) return 0;
    if (level <= 1) return 1;
    if (level <= 2) return 2;
    if (level <= 3) return 3;
    if (level <= 4) return 4;
    if (level <= 5) return 5;
    if (level <= 6) return 6;
    if (level <= 7) return 7;
    if (level <= 8) return 8;
    if (level <= 9) return 9;
    return 9;
  }
  if (charset == 1) { // blocks
    if (level <= 0) return 0;
    if (level <= 1) return 10;
    if (level <= 2) return 11;
    if (level <= 3) return 12;
    if (level <= 4) return 13;
    return 13;
  }
  if (charset == 2) { // minimal
    if (level <= 0) return 0;
    if (level <= 1) return 14;
    if (level <= 2) return 15;
    return 15;
  }
  if (charset == 3) { // dots
    if (level <= 0) return 0;
    if (level <= 1) return 16;
    if (level <= 2) return 17;
    if (level <= 3) return 18;
    if (level <= 4) return 19;
    if (level <= 5) return 20;
    return 20;
  }
  if (charset == 4) { // custom
    if (level <= 0) return 0;
    if (level <= 1) return 1;
    if (level <= 2) return 21;
    if (level <= 3) return 22;
    if (level <= 4) return 23;
    if (level <= 5) return 24;
    if (level <= 6) return 25;
    return 25;
  }
  if (charset == 5) { // braille
    if (level <= 0) return 0;
    if (level <= 1) return 26;
    if (level <= 2) return 27;
    if (level <= 3) return 28;
    if (level <= 4) return 29;
    if (level <= 5) return 30;
    if (level <= 6) return 31;
    return 31;
  }
  if (charset == 6) { // boxes
    if (level <= 0) return 0;
    if (level <= 1) return 32;
    if (level <= 2) return 33;
    if (level <= 3) return 34;
    if (level <= 4) return 35;
    if (level <= 5) return 36;
    return 36;
  }
  if (charset == 7) { // arrows
    if (level <= 0) return 0;
    if (level <= 1) return 37;
    if (level <= 2) return 21;
    if (level <= 3) return 38;
    if (level <= 4) return 39;
    if (level <= 5) return 40;
    if (level <= 6) return 41;
    return 41;
  }
  if (charset == 8) { // punct
    if (level <= 0) return 0;
    if (level <= 1) return 42;
    if (level <= 2) return 43;
    if (level <= 3) return 44;
    if (level <= 4) return 45;
    if (level <= 5) return 46;
    if (level <= 6) return 47;
    if (level <= 7) return 48;
    return 48;
  }
  if (charset == 9) { // numeric
    if (level <= 0) return 0;
    if (level <= 1) return 14;
    if (level <= 2) return 49;
    if (level <= 3) return 50;
    if (level <= 4) return 51;
    if (level <= 5) return 52;
    if (level <= 6) return 53;
    if (level <= 7) return 54;
    if (level <= 8) return 55;
    if (level <= 9) return 56;
    return 56;
  }
  return 0;
}

// highest ramp LEVEL per charset (= ramp length - 1)
float fsRampMaxFor(int charset) {
  if (charset == 0) return 9.0; // classic
  if (charset == 1) return 4.0; // blocks
  if (charset == 2) return 2.0; // minimal
  if (charset == 3) return 5.0; // dots
  if (charset == 4) return 6.0; // custom
  if (charset == 5) return 6.0; // braille
  if (charset == 6) return 5.0; // boxes
  if (charset == 7) return 6.0; // arrows
  if (charset == 8) return 7.0; // punct
  if (charset == 9) return 9.0; // numeric
  return 1.0;
}
`

export const ASCII_COMMON_GLSL = /* glsl */ `
uniform float uFsAscOn;
uniform float uFsAscCharset;
uniform float uFsAscCell;
uniform float uFsAscDensity;
uniform float uFsAscContrast;
uniform float uFsAscAnim;
uniform float uFsAscTime;
uniform float uFsAscDirX;
uniform float uFsAscDirY;
uniform float uFsAscLockScreen;
uniform float uFsAscReveal;
uniform float uFsAscAmount;
uniform float uFsAscBlend;

${GLYPH_TABLE_GLSL}

// Cheap per-cell hash, for flicker / rain column offsets.
float fsAscHash(vec2 p) {
  return fract(sin(dot(p, vec2(41.7, 289.3))) * 27183.19);
}

// Is pixel (gx, gy) of glyph idx filled? Bit index = gx + 5*gy, split across
// the lo/hi halves because a 25-bit value does not survive as a single float.
float fsGlyphPixel(int idx, vec2 g) {
  if (g.x < 0.0 || g.x > 4.0 || g.y < 0.0 || g.y > 4.0) return 0.0;
  vec2 bits = fsGlyphBits(idx);
  float a = g.x + 5.0 * g.y;
  float src = a < 13.0 ? bits.x : bits.y;
  float shift = a < 13.0 ? a : a - 13.0;
  return mod(floor(src / pow(2.0, shift)), 2.0);
}

// ROUND DOTS.
//
// The glyph table is a 5x5 BITMAP, and the bitmap sampler above quantises the
// cell with floor(): a lit bit fills its whole 1/5-of-a-cell square, hard edge
// to hard edge. For letterforms that is exactly right — the strokes of a '#' or
// a box-drawing glyph ARE square-ended. For the DOT alphabets it is not: the
// braille cells the Marquee stack lights up along the neon tube are supposed to
// read as BULBS, and a bulb is round. They were rendering as squares because
// nothing in this shader ever drew a circle.
//
// This samples the same bitmap CONTINUOUSLY. Work in glyph-pixel space (the
// cell is 5x5 units), and for the 3x3 neighbourhood of lit bits around the
// current position measure the distance to each bit's centre. Coverage is a
// radial falloff about that centre, and the neighbourhood max composites
// touching dots into one blob instead of clipping them at the bit boundary.
//
//   |  d < CORE          full brightness — the filament
//   |  CORE < d < EDGE   smoothstep shoulder — the glass, and the antialias
//   |  d > EDGE          off
//
// EDGE is deliberately just under half a glyph pixel (0.46) so neighbouring
// bulbs keep a dark gap between them: a marquee is a row of separate lamps, and
// the gap is what makes you read it as lamps rather than as a lit tube.
#define FS_BULB_CORE 0.24
#define FS_BULB_EDGE 0.46

float fsGlyphDot(int idx, vec2 inCell) {
  vec2 gp = inCell * 5.0;           // position in glyph-pixel units
  vec2 base = floor(gp);
  float cov = 0.0;
  for (int dy = -1; dy <= 1; dy++) {
    for (int dx = -1; dx <= 1; dx++) {
      vec2 g = base + vec2(float(dx), float(dy));
      if (fsGlyphPixel(idx, g) < 0.5) continue;
      float d = length(gp - (g + 0.5));
      cov = max(cov, 1.0 - smoothstep(FS_BULB_CORE, FS_BULB_EDGE, d));
    }
  }
  return cov;
}

// Which charsets are drawn as round bulbs rather than as bitmap glyphs.
//
// BRAILLE ONLY (5), deliberately. The 'dots' charset (3) is also a dot
// alphabet, and round would be conceptually right there too, but it is used by
// Sparse Glyph at an 8px cell — a glyph pixel is then 1.6 device pixels, which
// has no room to read as a circle and only loses light: measured over the ink
// region, mean luminance fell 57.8 -> 21.7 (-62%) when that preset was rendered
// with round dots, turning a "subtle overlay" into almost nothing. Braille runs
// at the Marquee stack's 22px cell (4.4px per glyph pixel), which is enough
// room for a bulb. If 'dots' is ever wanted round, its presets need re-tuning
// for the lost coverage first.
bool fsIsDotCharset(int charset) {
  return charset == 5;
}
`

/**
 * ASCII as a COMPOSABLE FUNCTION (see the dither module for why: an inline
 * block that mutates gl_FragColor can only run where it was pasted, which makes
 * layer reordering impossible).
 */
export const ASCII_APPLY_GLSL = /* glsl */ `
vec3 fsApplyAscii(vec3 fsAC, float fsNdV) {
  if (uFsAscOn < 0.5) return fsAC;

  // --- 1. the cell grid -------------------------------------------------
  vec2 fsACo = uFsAscLockScreen > 0.5
    ? gl_FragCoord.xy / max(uFsAscCell, 2.0)
    : vFsObjPos.xy * (150.0 / max(uFsAscCell, 2.0));

  vec2 fsDir = vec2(uFsAscDirX, uFsAscDirY);
  if (uFsAscAnim > 0.5 && uFsAscAnim < 1.5) {
    fsACo += fsDir * uFsAscTime;                 // scroll: whole grid travels
  } else if (uFsAscAnim < 2.5 && uFsAscAnim > 1.5) {
    // rain: each COLUMN falls at its own speed, so glyphs stream downward
    float col = floor(fsACo.x);
    fsACo.y += uFsAscTime * (0.6 + fsAscHash(vec2(col, 3.0)) * 1.8);
  }

  vec2 fsCell = floor(fsACo);
  vec2 fsInCell = fract(fsACo);

  // --- 2. brightness -> which character ---------------------------------
  float fsARaw = dot(fsAC, vec3(0.2126, 0.7152, 0.0722));

  // FORM TONE, then the shared TONE WINDOW (see style-shader.ts). The previous
  // divide-by-reference could only scale the subject's tone, and the subject
  // does not have a range to scale: measured over a real frame, the Solid
  // engine's ink is p25 = p50 = p75 = 0.538. Every cell therefore resolved to
  // the SAME ramp level and every charset rendered as one repeated character
  // (docs/verification/style-craft/sheets/solid_ascii_macro.png). Density
  // slides the window, contrast narrows it — and the contrast dial, which
  // previously produced five identical frames across its whole range, now
  // changes how many distinct characters appear.
  float fsAForm = fsFormTone(fsARaw, fsNdV);
  float fsALum = fsToneWindow(fsAForm, uFsAscDensity, uFsAscContrast * 0.72);

  // revealDensity acts BEFORE quantization.
  //
  // It used to act after — 'fsLevel = floor(fsLevel * reveal + 0.5)' on an
  // (NB: single quotes, not backticks — this comment is inside a GLSL template
  // literal, so a backtick here terminates the string and breaks the build.)
  // already-integer level — which has two failures in one line. It is
  // bit-identical to no animation whenever the playhead rests at 1 (the state
  // the user judges the preset in, and the state the whole rail is browsed in),
  // and while the draw-in IS running it moves in whole ramp steps, so the
  // "density grows" it advertises arrives as three or four visible jumps.
  // Scaling the continuous tone instead gives a smooth build, and the same
  // identity at rest is then a property of the effect being finished rather
  // than of the arithmetic collapsing.
  if (uFsAscAnim > 4.5) {
    fsALum *= clamp(uFsAscReveal, 0.0, 1.0);
  }

  float fsRampMax = fsRampMaxFor(int(uFsAscCharset + 0.5));
  float fsLevel = floor(fsALum * fsRampMax + 0.5);

  if (uFsAscAnim > 2.5 && uFsAscAnim < 3.5) {
    // cycle: every cell walks up the ramp over time (glyphs change in place).
    //
    // THE PHASE IS PER-CELL. Without the hash term every cell walked the ramp
    // in lockstep, which means the whole form passed through the ramp's BLANK
    // glyph at the same instant — a full-frame flash to dark, roughly every
    // 3.3s. Read it in docs/verification/screen-layers/after/sheets/
    // motion_asc_cycle_strip.png: f6 is a dense weave, f12 is an almost empty
    // silhouette, f36 is dense again, f42 empty. In the numbers it is the
    // worst strobe signature in the family — mean frame delta 7.9 with a peak
    // of 43.7 and a floor of 0.0, i.e. long stretches of nothing punctuated by
    // one enormous jump. A global luminance flash is the first thing an
    // animation review fails, and nothing about "characters change in place"
    // requires the changes to be simultaneous.
    //
    // Offsetting by a per-cell random multiple of the ramp length keeps every
    // cell on the same speed and the same ramp — so it is still one coherent
    // behaviour, not noise — while the blank glyph is reached at a different
    // time in each cell. The form now shimmers instead of blinking.
    float fsCycPhase = fsAscHash(fsCell) * (fsRampMax + 1.0);
    fsLevel = mod(fsLevel + floor(uFsAscTime * 3.0 + fsCycPhase), fsRampMax + 1.0);
  } else if (uFsAscAnim > 3.5 && uFsAscAnim < 4.5) {
    // flicker: a few cells jump to a random glyph each tick
    float tick = floor(uFsAscTime * 8.0);
    float r = fsAscHash(fsCell + tick);
    if (r > 0.86) fsLevel = floor(fsAscHash(fsCell + tick + 7.0) * fsRampMax + 0.5);
  }
  // (revealDensity is handled above, before quantization.)

  int fsCharset = int(uFsAscCharset + 0.5);
  int fsIdx = fsRampIndex(fsCharset, int(fsLevel + 0.5));

  // --- 3. draw the glyph ------------------------------------------------
  // 5x5 bitmap sampled inside the cell; y is flipped because glyph row 0 is the
  // TOP row while gl_FragCoord.y grows upward.
  //
  // Letterforms take the bitmap straight (floor() -> square bit cells, which is
  // what a character stroke should be). Dot alphabets go through fsGlyphDot
  // instead, which reads the same bits as ROUND bulbs with a falloff — see the
  // note there; the Marquee stack's braille cells are bulbs on a sign, and a
  // square bulb is just a mistake.
  vec2 fsCellUV = vec2(fsInCell.x, 1.0 - fsInCell.y);
  float fsOn = fsIsDotCharset(fsCharset)
    ? fsGlyphDot(fsIdx, fsCellUV)
    : fsGlyphPixel(fsIdx, floor(fsCellUV * 5.0));

  // Lit glyph pixels must be MUCH brighter than unlit ones or the characters
  // are invisible on dark ink (multiplying near-black by 1.35 is still
  // near-black). Divide the colour by its own luminance to get the surface's
  // hue with brightness normalised away, then drive brightness explicitly:
  // bright for lit glyph pixels, near-black for the rest. This keeps material
  // presets distinguishable instead of collapsing every surface to white.
  vec3 fsATint = fsARaw > 0.002 ? fsAC / fsARaw : vec3(1.0);
  // Both ends track tone as well as the glyph does. A fixed on/off pair threw
  // away every bit of shading that did not survive the (coarse) ramp
  // quantization, so the form read as a black silhouette wearing wallpaper.
  // Letting the lit pixels brighten with tone is the cheapest way to carry the
  // continuous part of the shading through a discrete alphabet, and giving the
  // unlit pixels a small tonal lift keeps the object legible as an object.
  vec3 fsOnCol = clamp(fsATint * (0.55 + 0.42 * fsALum), 0.0, 1.0);
  vec3 fsOffCol = clamp(fsATint * (0.04 + 0.11 * fsALum), 0.0, 1.0);
  vec3 fsGlyphed = mix(fsOffCol, fsOnCol, fsOn);

  return fsStackBlend(fsAC, fsGlyphed, uFsAscBlend, uFsAscAmount);
}
`
